# Generated by Django 6.0.1 on 2026-01-29 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(default='bi-question-circle', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(default='EEMTI PMBC', max_length=100)),
                ('cor_primaria', models.CharField(default='#0A2619', help_text='Cor Hexadecimal (Ex: #0A2619)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#D4AF37', help_text='Cor Hexadecimal (Ex: #D4AF37)', max_length=7)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=100)),
                ('ano_letivo', models.IntegerField(default=2026)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='planos_ensino/')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 3º Ano B', max_length=50)),
                ('ano_letivo', models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('tema', models.CharField(blank=True, max_length=100, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
            options={
                'ordering': ['disciplina', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('numero_chamada', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('RECUPERACAO', 'Recuperação'), ('FORMADO', 'Formado/Concluinte'), ('TRANSFERIDO', 'Transferido')], default='CURSANDO', max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_matriculados', to='core.turma')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'unique_together': {('aluno', 'turma')},
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')], default=3)),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/')),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], default='M', max_length=1)),
                ('alternativa_a', models.CharField(max_length=500)),
                ('alternativa_b', models.CharField(max_length=500)),
                ('alternativa_c', models.CharField(max_length=500)),
                ('alternativa_d', models.CharField(max_length=500)),
                ('alternativa_e', models.CharField(blank=True, max_length=500, null=True)),
                ('gabarito', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('descritor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descritor')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='ItemGabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('resposta_correta', models.CharField(max_length=1)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_gabarito', to='core.avaliacao')),
                ('descritor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descritor')),
                ('questao_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questao')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to='core.questao'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField()),
                ('total_questoes', models.IntegerField()),
                ('percentual', models.FloatField(blank=True, editable=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('ADQ', 'Adequado'), ('INT', 'Intermediário'), ('CRI', 'Crítico'), ('MCR', 'Muito Crítico')], editable=False, max_length=3, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avaliacao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaDetalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField(default=False)),
                ('item_gabarito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemgabarito')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questao')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_detalhadas', to='core.resultado')),
            ],
        ),
        migrations.CreateModel(
            name='TopicoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(choices=[(1, '1º'), (2, '2º'), (3, '3º'), (4, '4º')])),
                ('conteudo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('TODO', 'A Planejar'), ('DOING', 'Em Aula'), ('DONE', 'Concluído')], default='TODO', max_length=10)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='core.planoensino')),
            ],
        ),
        migrations.AddField(
            model_name='planoensino',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma'),
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('publico', models.CharField(choices=[('PROF', 'Professor / Gestão'), ('ALUNO', 'Aluno / Responsável'), ('TODOS', 'Todos')], default='PROF', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link_video', models.URLField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaajuda')),
            ],
        ),
        migrations.CreateModel(
            name='NDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField(default=1)),
                ('nota_frequencia', models.FloatField(default=0)),
                ('nota_atividade', models.FloatField(default=0)),
                ('nota_comportamento', models.FloatField(default=0)),
                ('nota_prova_parcial', models.FloatField(default=0)),
                ('nota_prova_bimestral', models.FloatField(default=0)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='core.matricula')),
            ],
            options={
                'unique_together': {('matricula', 'bimestre')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='planoensino',
            unique_together={('turma', 'disciplina_nome', 'ano_letivo')},
        ),
    ]
