# Generated by Django 6.0 on 2026-01-07 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True, verbose_name='Matrícula Ativa')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 1º Ano A - T.I.', max_length=50)),
                ('ano_letivo', models.IntegerField(default=2026)),
            ],
        ),
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('tema', models.CharField(blank=True, help_text='Ex: Geometria, Termodinâmica', max_length=100, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Descritor / Habilidade',
                'verbose_name_plural': 'Descritores',
                'ordering': ['disciplina', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Prova Global - 1º Bimestre', max_length=100)),
                ('data_aplicacao', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='questoes/', verbose_name='Imagem de Apoio')),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], default='M', max_length=1)),
                ('alternativa_a', models.CharField(max_length=500)),
                ('alternativa_b', models.CharField(max_length=500)),
                ('alternativa_c', models.CharField(max_length=500)),
                ('alternativa_d', models.CharField(max_length=500)),
                ('alternativa_e', models.CharField(blank=True, max_length=500, null=True)),
                ('gabarito', models.CharField(choices=[('A', 'Letra A'), ('B', 'Letra B'), ('C', 'Letra C'), ('D', 'Letra D'), ('E', 'Letra E')], max_length=1)),
                ('descritor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descritor', verbose_name='Habilidade Associada')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Banco de Questões',
            },
        ),
        migrations.CreateModel(
            name='ItemGabarito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('resposta_correta', models.CharField(max_length=1)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_gabarito', to='core.avaliacao')),
                ('descritor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.descritor')),
                ('questao_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questao')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('avaliacao', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to='core.questao'),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField()),
                ('total_questoes', models.IntegerField()),
                ('percentual', models.FloatField(blank=True, editable=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('ADQ', 'Adequado (75-100%)'), ('INT', 'Intermediário (50-74%)'), ('CRI', 'Crítico (25-49%)'), ('MCR', 'Muito Crítico (0-24%)')], editable=False, max_length=3, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaDetalhada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertou', models.BooleanField(default=False)),
                ('item_gabarito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.itemgabarito')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.questao')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_detalhadas', to='core.resultado')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma'),
        ),
    ]
