# Generated by Django 6.0.1 on 2026-01-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respostadetalhada',
            name='resposta_aluno',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
