# Generated by Django 6.0 on 2026-01-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaosistema',
            name='cor_destaque',
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='cor_secundaria',
            field=models.CharField(default='#3b82f6', help_text='Cor Hexadecimal (Ex: #3b82f6)', max_length=7),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='cor_primaria',
            field=models.CharField(default='#0f172a', help_text='Cor Hexadecimal (Ex: #0f172a)', max_length=7),
        ),
    ]
