# Generated by Django 6.0 on 2026-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='serie',
            field=models.IntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')], default=3, verbose_name='Série Alvo'),
        ),
    ]
