# Generated by Django 6.0.1 on 2026-02-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_respostadetalhada_resposta_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matricula'),
        ),
    ]
