# Generated by Django 6.0 on 2026-01-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_questao_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.aluno'),
        ),
    ]
