# Generated by Django 6.0 on 2026-01-28 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_configuracaosistema_cor_destaque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(default='bi-question-circle', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Texto Explicativo')),
                ('publico', models.CharField(choices=[('PROF', 'Professor / Gestão'), ('ALUNO', 'Aluno / Responsável'), ('TODOS', 'Todos')], default='PROF', max_length=10)),
                ('link_video', models.URLField(blank=True, help_text='Cole o link de embed do YouTube', null=True)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='tutoriais/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriaajuda')),
            ],
        ),
    ]
