# Generated by Django 6.0.1 on 2026-02-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_avaliacao_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('disciplinas', models.ManyToManyField(related_name='professores', to='core.disciplina')),
                ('turmas', models.ManyToManyField(related_name='professores', to='core.turma')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
