# Generated by Django 6.0.1 on 2026-02-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='arquivo_pei',
            field=models.FileField(blank=True, null=True, upload_to='pei_alunos/', verbose_name='Documento PEI/Laudo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cor_raca',
            field=models.CharField(choices=[('BRANCA', 'Branca'), ('PRETA', 'Preta'), ('PARDA', 'Parda'), ('AMARELA', 'Amarela'), ('INDIGENA', 'Indígena'), ('NAO_DECLARADO', 'Não Declarado')], default='NAO_DECLARADO', max_length=20, verbose_name='Cor/Raça'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('NB', 'Não-Binário'), ('OUTRO', 'Outro')], default='M', max_length=10, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='is_pcd',
            field=models.BooleanField(default=False, verbose_name='É PcD / Inclusão?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes_clinicas',
            field=models.TextField(blank=True, help_text='Cuidados específicos, medicação, suporte necessário.', null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='possui_computador',
            field=models.BooleanField(default=False, verbose_name='Possui Computador/Tablet?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='renda_familiar',
            field=models.CharField(blank=True, choices=[('BAIXA', 'Até 1 Salário Mínimo (Baixa Renda)'), ('MEDIA_BAIXA', '1 a 3 Salários Mínimos'), ('MEDIA', '3 a 6 Salários Mínimos'), ('ALTA', 'Acima de 6 Salários Mínimos')], max_length=20, null=True, verbose_name='Renda Familiar'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_acesso_internet',
            field=models.CharField(choices=[('SEM', 'Sem acesso à internet'), ('MOVEL', 'Apenas dados móveis (Celular)'), ('FIXA', 'Banda Larga / Wi-Fi')], default='FIXA', max_length=10, verbose_name='Acesso Digital'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, choices=[('TEA', 'Transtorno do Espectro Autista (TEA)'), ('TDAH', 'TDAH (Laudo Clínico)'), ('DV', 'Deficiência Visual / Baixa Visão'), ('DA', 'Deficiência Auditiva'), ('DF', 'Deficiência Física/Motora'), ('DI', 'Deficiência Intelectual'), ('AH', 'Altas Habilidades / Superdotação'), ('OUTRA', 'Outra Necessidade Específica')], max_length=10, null=True, verbose_name='Tipo de Condição'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='media_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='status',
            field=models.CharField(choices=[('CURSANDO', 'Cursando'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('RECUPERACAO', 'Em Recuperação Final'), ('FORMADO', 'Formado/Concluinte'), ('TRANSFERIDO', 'Transferido')], default='CURSANDO', max_length=20),
        ),
    ]
