# Generated by Django 6.0.1 on 2026-03-10 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_aluno_usuario_alter_descritor_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descritor',
            options={'ordering': ['matriz', 'disciplina', 'codigo']},
        ),
        migrations.AddField(
            model_name='descritor',
            name='descritor_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_filhas', to='core.descritor'),
        ),
        migrations.AddField(
            model_name='descritor',
            name='matriz',
            field=models.CharField(choices=[('SPAECE', 'SPAECE - Ceará'), ('SAEB', 'SAEB - Nacional'), ('ENEM', 'Matriz ENEM')], default='SPAECE', max_length=15),
        ),
        migrations.AlterField(
            model_name='descritor',
            name='codigo',
            field=models.CharField(help_text='Ex: S01, S01H01, H12', max_length=20),
        ),
    ]
