# Generated by Django 6.0.1 on 2026-03-23 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_descritor_options_descritor_descritor_pai_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='core.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='core.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='core.turma')),
            ],
            options={
                'verbose_name': 'Alocação de Aula',
                'verbose_name_plural': 'Alocações de Aulas',
                'unique_together': {('professor', 'disciplina', 'turma')},
            },
        ),
    ]
