# Generated by Django 6.0.1 on 2026-03-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='core.alocacao'),
        ),
        migrations.AddField(
            model_name='planoensino',
            name='alocacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_ensino', to='core.alocacao'),
        ),
    ]
