# Generated by Django 6.0.1 on 2026-03-24 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_avaliacao_alocacao_planoensino_alocacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='turma',
        ),
        migrations.AlterUniqueTogether(
            name='planoensino',
            unique_together={('alocacao', 'ano_letivo')},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='turmas',
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='alocacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='core.alocacao'),
        ),
        migrations.AlterField(
            model_name='planoensino',
            name='alocacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_ensino', to='core.alocacao'),
        ),
        migrations.RemoveField(
            model_name='planoensino',
            name='disciplina_nome',
        ),
        migrations.RemoveField(
            model_name='planoensino',
            name='turma',
        ),
    ]
