# Generated by Django 6.0.1 on 2026-04-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_avaliacao_disciplina_remove_avaliacao_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descritor',
            name='area_enem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área do ENEM'),
        ),
        migrations.AddField(
            model_name='descritor',
            name='competencia',
            field=models.TextField(blank=True, null=True, verbose_name='Competência do ENEM'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='area_enem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Área do ENEM'),
        ),
        migrations.AlterField(
            model_name='descritor',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.disciplina'),
        ),
    ]
