# Generated by Django 6.0.1 on 2026-04-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_descritor_area_enem_descritor_competencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ndi',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ndi',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ndis', to='core.disciplina'),
        ),
        migrations.AlterUniqueTogether(
            name='ndi',
            unique_together={('matricula', 'bimestre', 'disciplina')},
        ),
    ]
