# Generated by Django 6.0.1 on 2026-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ndi_unique_together_ndi_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndi',
            name='nota_atividade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndi',
            name='nota_comportamento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndi',
            name='nota_frequencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndi',
            name='nota_prova_bimestral',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ndi',
            name='nota_prova_parcial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
