# Generated by Django 6.0.1 on 2026-04-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ndi_nota_atividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='acertos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='percentual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
