# Generated by Django 6.0.1 on 2026-04-19 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_resultado_acertos_alter_resultado_percentual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Área de Conhecimento',
                'verbose_name_plural': 'Áreas de Conhecimento',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='area_conhecimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='core.areaconhecimento'),
        ),
        migrations.CreateModel(
            name='CoordenadorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('areas_conhecimento', models.ManyToManyField(related_name='coordenadores', to='core.areaconhecimento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pca_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordenador de Área (PCA)',
                'verbose_name_plural': 'Coordenadores de Área (PCAs)',
            },
        ),
    ]
